# Generated by Django 4.1.2 on 2022-10-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('backend', models.BooleanField(verbose_name=True)),
                ('age', models.IntegerField()),
                ('bio', models.TextField(max_length=255)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
    ]
